[[redirects]]
  from = "https://leretro.org"
  to = "https://www.leretroprojecteur.com"
  status = 301
  force = true
  conditions = {Language = ["en"], Country = ["US"]}

[[redirects]]
  from = "https://www.leretro.org"
  to = "https://leretroprojecteur.com"
  status = 301
  force = false
  conditions = {Language = ["en"], Country = ["US"]}
