import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";
import type { Metadata } from "next";

import { setDefaultOptions } from "date-fns";
import { fr } from "date-fns/locale";

import Footer from "../components/footer";
import Header from "../components/header";
import "./globals.css";

config.autoAddCss = false;

setDefaultOptions({ locale: fr });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="fr">
      <body className="light-theme">
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
